name: Snyk - Software Bill of Materials (SBOM)
on:
  release:
    types: [published]

jobs:
  sbom:
    permissions:
      contents: write
    uses: mattermost/actions-workflows/.github/workflows/snyk-sbom.yml@8401a73d1a168f520dc08fabcfb1600dec1176ef
    secrets: inherit
